// Single source of truth for what the platform backend supports today.
// live: the console already does this. api: the platform supports it but the
// console has no UI. new: no platform support; needs a backend contract.
export type BackingStatus = 'live' | 'api' | 'new'

export type Backing = {
  id: string
  section: string
  title: string
  status: BackingStatus
  note: string
  /** Issue numbers on supabricks/platform. */
  issues?: number[]
}

export const BACKING: Backing[] = [
  { id: 'DB-01', section: 'Databases', title: 'Database list', status: 'live', note: 'Root databases are listed today as branches with no parent.' },
  { id: 'DB-02a', section: 'Databases', title: 'Provision database (name)', status: 'live', note: 'database create NAME.' },
  { id: 'DB-02b', section: 'Databases', title: 'Provision with compute size, auto-suspend and Postgres version', status: 'new', note: 'No compute sizing or auto-suspend setting exists; the version is fixed at PostgreSQL 17.', issues: [244, 245] },
  { id: 'DB-03', section: 'Database detail', title: 'Overview: storage used and connection count', status: 'new', note: 'State and default branch exist. Storage size and live connection counts are not reported.', issues: [246] },
  { id: 'DB-04a', section: 'Database detail', title: 'Connection URI', status: 'live', note: 'connect [BRANCH] --uri returns application credentials.' },
  { id: 'DB-04b', section: 'Database detail', title: 'psql, JDBC, .env and driver snippets', status: 'live', note: 'Console-side renderings of the same credentials; no backend change.' },
  { id: 'DB-04c', section: 'Database detail', title: 'Reset password', status: 'new', note: 'No credential rotation command for application roles.', issues: [250] },
  { id: 'DB-04d', section: 'Database detail', title: 'Pooled connections', status: 'new', note: 'There is a connection gateway (256 connections) but no pooling mode.', issues: [252] },
  { id: 'DB-05', section: 'Database detail', title: 'API keys', status: 'new', note: 'No key system. Local access is the launch session; governed access is OIDC sign-in.', issues: [249] },
  { id: 'DB-06a', section: 'Database detail', title: 'Suspend and resume compute', status: 'live', note: 'branch suspend / resume.' },
  { id: 'DB-06b', section: 'Database detail', title: 'Scale compute up or down', status: 'new', note: 'No compute size setting in the native product.', issues: [244] },
  { id: 'DB-06c', section: 'Database detail', title: 'Auto-suspend timeout', status: 'new', note: 'Computes wake on connection, but idle suspend is not user-configurable.', issues: [245] },
  { id: 'DB-07', section: 'Database detail', title: 'Observability: metrics, slow and active queries, locks', status: 'new', note: 'No metrics endpoint. Data would come from pg_stat views and the process supervisor.', issues: [247, 248] },
  { id: 'DB-08', section: 'Database detail', title: 'Roles and privileges', status: 'new', note: 'Possible through SQL today; no dedicated command or UI.', issues: [251] },
  { id: 'DB-09', section: 'Database detail', title: 'Extensions', status: 'new', note: 'The bundle preloads only the neon extension; no extension catalogue.', issues: [253] },
  { id: 'DB-10a', section: 'Database detail', title: 'Point-in-time restore to a new branch', status: 'api', note: 'branch create --at-time / --at-lsn exists; the console has no UI for it.' },
  { id: 'DB-10b', section: 'Database detail', title: 'Backup bundles', status: 'api', note: 'backup create / verify / restore are CLI-only and require stopping the cell.' },
  { id: 'DB-10c', section: 'Database detail', title: 'History retention window', status: 'new', note: 'Retention is not exposed or configurable.', issues: [254] },
  { id: 'DB-11a', section: 'Database detail', title: 'Rename and set default branch', status: 'api', note: 'branch rename and branch default exist; the console has no UI.' },
  { id: 'DB-11b', section: 'Database detail', title: 'Delete database', status: 'live', note: 'branch delete with typed confirmation.' },
  { id: 'BR-01', section: 'Branches', title: 'Branch list', status: 'live', note: 'Flat table today; the tree view is console-side.' },
  { id: 'BR-01b', section: 'Branches', title: 'Storage difference from parent', status: 'new', note: 'Per-branch storage size is not reported.', issues: [246] },
  { id: 'BR-02a', section: 'Branches', title: 'Create branch from current head', status: 'live', note: 'branch create NAME --from PARENT.' },
  { id: 'BR-02b', section: 'Branches', title: 'Create branch at a time or log position, with expiry', status: 'api', note: '--at-time, --at-lsn and branch ttl exist; the console has no UI.' },
  { id: 'BR-04a', section: 'Branches', title: 'Suspend, resume, delete', status: 'live', note: 'Available in the console today.' },
  { id: 'BR-04b', section: 'Branches', title: 'Rename, set default, set expiry', status: 'api', note: 'Supported by the platform; no console UI.' },
  { id: 'BR-05', section: 'Branches', title: 'Schema diff between branches', status: 'new', note: 'No diff command.', issues: [255] },
  { id: 'BR-06', section: 'Branches', title: 'Reset branch from parent', status: 'new', note: 'No reset operation; today you delete and recreate.', issues: [256] },
  { id: 'TE-01', section: 'Table editor', title: 'Table list with row estimates and sizes', status: 'new', note: 'The catalog command returns tables and columns only.', issues: [257] },
  { id: 'TE-02a', section: 'Table editor', title: 'Browse rows', status: 'live', note: 'Preview runs SELECT * LIMIT 200; results cap at 1,000 rows / 256 KiB.' },
  { id: 'TE-02b', section: 'Table editor', title: 'Paging, sorting and filtering beyond 1,000 rows', status: 'new', note: 'Needs a paged read contract; the SQL action returns one bounded result.', issues: [257] },
  { id: 'TE-02c', section: 'Table editor', title: 'Inline edit, insert and delete rows', status: 'new', note: 'Writes are possible as single SQL statements; a batched edit contract is missing.', issues: [258] },
  { id: 'TE-03', section: 'Table editor', title: 'Create and alter table', status: 'new', note: 'Possible as SQL with writes enabled; no DDL-generation contract.', issues: [259] },
  { id: 'TE-04', section: 'Table editor', title: 'Indexes, constraints, triggers, policies, DDL', status: 'new', note: 'Not returned by the catalog command.', issues: [260] },
  { id: 'SQ-01', section: 'SQL editor', title: 'Run a statement, cancel, tabs', status: 'live', note: 'One statement, 32 KiB, 8 tabs, read-only by default.' },
  { id: 'SQ-01b', section: 'SQL editor', title: 'Multiple statements and run selection', status: 'new', note: 'The SQL action accepts one statement.', issues: [261] },
  { id: 'SQ-03b', section: 'SQL editor', title: 'Query plan view', status: 'new', note: 'EXPLAIN can be run as SQL; no structured plan output.', issues: [261] },
  { id: 'SQ-04', section: 'SQL editor', title: 'Saved queries', status: 'live', note: 'Saved per project; flat list today.' },
  { id: 'SQ-05', section: 'SQL editor', title: 'Query history', status: 'new', note: 'Query IDs exist, but there is no history listing.', issues: [261] },
  { id: 'OE-01a', section: 'Object explorer', title: 'Tables and columns', status: 'live', note: 'catalog [--branch] returns tables and columns (up to 1,000 columns).' },
  { id: 'OE-01b', section: 'Object explorer', title: 'Views, functions, sequences, types, indexes', status: 'new', note: 'Not returned by the catalog command.', issues: [260] },
  { id: 'SY-01', section: 'Sync', title: 'Sync pipeline per branch: create, list, show', status: 'live', note: 'sync create / list / show. The platform calls a pipeline a policy.' },
  { id: 'SY-01b', section: 'Sync', title: 'More than one incremental pipeline per installation', status: 'new', note: 'Triggered and continuous modes share one capture and one materializer per installation, and one policy per branch.', issues: [264] },
  { id: 'SY-02a', section: 'Sync', title: 'Snapshot, triggered and continuous modes with schedule, freshness and batch settings', status: 'live', note: 'Schedule 60 s to 30 days (UTC, missed runs coalesced); freshness 1 to 300 s; batch interval 0.2 to 60 s.' },
  { id: 'SY-02b', section: 'Sync', title: 'Choose which tables a pipeline syncs', status: 'new', note: 'Sync covers the whole branch. One unsupported column blocks publication; no table is skipped.', issues: [265] },
  { id: 'SY-02c', section: 'Sync', title: 'Sync columns of type uuid, jsonb, bytea, float and arrays', status: 'new', note: 'Supported today: boolean, integers, text and varchar, bounded numeric, date, timestamp, timestamptz.', issues: [266] },
  { id: 'SY-02d', section: 'Sync', title: 'Storage profile and byte and time budgets', status: 'api', note: '--storage-profile and limits exist in the command schema; the console preserves budgets but cannot edit them.' },
  { id: 'SY-03a', section: 'Sync', title: 'Freshness, lag, log positions, backlog and budgets (current values)', status: 'live', note: 'continuous_status reports published, captured and source positions, lag, backlog, spool and retained WAL.' },
  { id: 'SY-03b', section: 'Sync', title: 'Lag and throughput history over time', status: 'new', note: 'Only current values are reported; no time series is kept.', issues: [267] },
  { id: 'SY-04', section: 'Sync', title: 'Run history, run now, cancel a run', status: 'live', note: 'sync runs / run / cancel. Up to 100 runs per request.' },
  { id: 'SY-05', section: 'Sync', title: 'Per-table row counts and last change', status: 'new', note: 'Runs report a published version and position, not per-table statistics.', issues: [268] },
  { id: 'SY-07', section: 'Sync', title: 'Pause, resume, reviewed full resync, delete', status: 'live', note: 'sync pause / resume / review-resync / resync / delete, with revision and key fencing.' },
  { id: 'SY-08', section: 'Sync', title: 'Blocked and pressure states', status: 'live', note: 'Policies report blocked, history loss and pressure at 80% of either capture budget. The console shows raw state strings today.' },
  { id: 'SY-09', section: 'Sync', title: 'Analytics to PostgreSQL sync', status: 'new', note: 'Reverse sync is deferred in the delivery ledger.', issues: [269] },
  { id: 'AN-01', section: 'Analytics', title: 'Read-only Spark SQL over a published version', status: 'live', note: 'analytics sql against a pinned session. Results cap at 1,000 rows / 256 KiB; deadline up to 30 s.' },
  { id: 'AN-01b', section: 'Analytics', title: 'Query a chosen older version', status: 'api', note: 'analytics open --epoch ID exists; the console can only open the latest, or one handed over from the Data page.' },
  { id: 'AN-02a', section: 'Analytics', title: 'Version history per branch', status: 'api', note: 'analytics epochs --branch lists history with paging; the console shows only the latest publication.' },
  { id: 'AN-02b', section: 'Analytics', title: 'Pin a version and clean up old ones', status: 'api', note: 'analytics pin / renew / unpin and analytics gc --keep N exist; no console UI.' },
  { id: 'AN-02c', section: 'Analytics', title: 'Version size and rows changed', status: 'new', note: 'Full exports record row counts and file sizes in their manifest; incremental versions do not report size or change counts through the API.', issues: [271] },
  { id: 'AN-03a', section: 'Analytics', title: 'Sessions: open, list, close, cancel; shared capacity', status: 'live', note: 'Two slots shared with notebooks and the CLI; sessions expire after 15 minutes and close after two minutes without a heartbeat.' },
  { id: 'AN-03b', section: 'Analytics', title: 'Compute profile per session', status: 'api', note: '--resource-profile compact|analytical exists; the console has no selector.' },
  { id: 'AN-03c', section: 'Analytics', title: 'Show what owns each session', status: 'new', note: 'Sessions are listed by ID, branch and version. The session record returned to clients does not say whether a notebook, SQL tab or CLI shell opened it.', issues: [272] },
  { id: 'AN-05', section: 'Analytics', title: 'Spark query history', status: 'new', note: 'Queries have IDs within a session; nothing persists after the session closes.', issues: [273] },
  { id: 'NB-01', section: 'Notebooks', title: 'Notebook files: list, new, rename, save a copy, download', status: 'live', note: 'Notebooks are .ipynb files in the project. The console lists them flat.' },
  { id: 'NB-01b', section: 'Notebooks', title: 'Folders, upload, duplicate and delete', status: 'new', note: 'No delete, upload or folder actions in the local console; governed import exists but strips outputs and caps at 22 KB.', issues: [275] },
  { id: 'NB-02', section: 'Notebooks', title: 'Jupyter editing: code and Markdown cells, run, run all, standard shortcuts', status: 'live', note: 'An embedded JupyterLab notebook widget. Cell source up to 64 KiB.' },
  { id: 'NB-02b', section: 'Notebooks', title: 'Rich outputs beyond text, HTML and images', status: 'new', note: 'Outputs are limited to text, Markdown, sanitized HTML, PNG and JPEG. Interactive widgets, SVG and JavaScript are not rendered.', issues: [276] },
  { id: 'NB-03', section: 'Notebooks', title: 'Kernel: start, stop, restart, interrupt, reconnect, restart on the latest version', status: 'live', note: 'Kernel states stopped, starting, ready, busy, interrupting, stopping, failed, lost, expired. A kernel holds an analytical session slot.' },
  { id: 'NB-05', section: 'Notebooks', title: 'Variable inspector and kernel memory and CPU', status: 'new', note: 'No kernel introspection or resource reporting.', issues: [277] },
  { id: 'NB-06', section: 'Notebooks', title: 'Python environment: add and remove packages, prepare, adopt, offline bundles', status: 'live', note: 'One managed environment per project with a lock file; running kernels adopt a prepared environment explicitly.' },
  { id: 'NB-07', section: 'Notebooks', title: 'Autosave and checkpoints', status: 'new', note: 'Saves are explicit and revision-checked. There is no autosave or checkpoint history.', issues: [278] },
  { id: 'UC-01', section: 'Catalog', title: 'Browse tables with columns, ownership and freshness', status: 'live', note: 'catalog metadata list / describe, backed by the bundled open-source Unity Catalog. The console shows one flat page today.' },
  { id: 'UC-02a', section: 'Catalog', title: 'Table and column descriptions', status: 'new', note: 'Catalog metadata is read-only through the platform: list, describe, resolve and validate. Comments come from PostgreSQL; they cannot be edited on analytical tables.', issues: [280] },
  { id: 'UC-02b', section: 'Catalog', title: 'Lineage across notebooks and columns', status: 'new', note: 'Observed provenance covers import to table and version to publication. Python and column-level lineage are not inferred.', issues: [281] },
  { id: 'UC-03a', section: 'Catalog', title: 'Publish a reviewed version to the catalog', status: 'live', note: 'catalog publication preview / publish, fenced by a preview hash and revisions. No data is copied for full snapshots.' },
  { id: 'UC-03b', section: 'Catalog', title: 'Publish a chosen subset of tables', status: 'new', note: 'A publication is always the complete table set of a version.', issues: [282] },
  { id: 'UC-04', section: 'Catalog', title: 'Publications: list, withdraw, resume, see who holds them', status: 'live', note: 'catalog publication status / resume / unpublish, with retention holders.' },
  { id: 'UC-05', section: 'Catalog', title: 'Shared datasets: discover, bind, review updates and removal', status: 'live', note: 'catalog datasets list / describe / references and reviewed project plans. Discovery alone grants nothing.' },
  { id: 'UC-06', section: 'Catalog', title: 'Catalog service: health, restart, rotate key, external metastore', status: 'api', note: 'catalog service status / restart / rotate-key / configure are CLI-only.' },
  { id: 'UC-07', section: 'Catalog', title: 'Table permissions by person or group', status: 'live', note: 'SELECT grants exist in the governed server profile only, through reviewed sharing plans. A local installation has one owner.' },
  { id: 'UC-08', section: 'Catalog', title: 'Usage: who queried a table and how often', status: 'new', note: 'Readers holding a version are known; query counts per table are not recorded.', issues: [283] },
  { id: 'HM-01', section: 'Home', title: 'Projects: list, create and open', status: 'live', note: 'The console home lists projects on this device and creates one with its main database.' },
  { id: 'HM-01b', section: 'Home', title: 'Rename, stop and delete a project', status: 'new', note: 'No project lifecycle actions beyond create and open.', issues: [287] },
  { id: 'HM-02', section: 'Home', title: 'Recent work across notebooks, queries, tables and pipelines', status: 'new', note: 'There is no record of recently opened items.', issues: [286] },
  { id: 'HM-03', section: 'Home', title: 'One activity feed across the project', status: 'new', note: 'Operations are tracked per feature (branches, imports, sync runs, environments). There is no combined, ordered history.', issues: [285] },
  { id: 'HM-04', section: 'Home', title: 'Health of each service', status: 'api', note: 'status and doctor report readiness per process on the command line; the console shows a single ready or not-ready pill.' },
  { id: 'HM-05', section: 'Home', title: 'Project map: databases, pipelines and analytical tables together', status: 'live', note: 'Assembled in the console from branch, sync and snapshot listings.' },
  { id: 'PJ-01', section: 'Project', title: 'Read the project definition: resources, dependencies, capabilities, targets', status: 'live', note: 'project inspect / validate read supabricks.toml offline and return the resource graph in apply order.' },
  { id: 'PJ-02', section: 'Project', title: 'Whether the folder matches what is installed', status: 'live', note: 'A hash of the declared files is compared with the installed revision.' },
  { id: 'PJ-02b', section: 'Project', title: 'Which resources changed since the last install', status: 'new', issues: [289], note: 'Only a whole-source hash is compared. There is no per-resource or per-file difference against the installed revision.' },
  { id: 'PJ-03', section: 'Project', title: 'Plan and apply: review steps, apply, cancel, recover by key', status: 'live', note: 'project plan / apply / status / cancel / find. Apply never deletes; removed resources are retained.' },
  { id: 'PJ-03b', section: 'Project', title: 'History of past applies', status: 'new', issues: [290], note: 'An apply can be read by ID or found by key. There is no list of past applies or revisions for a deployment.' },
  { id: 'PJ-04', section: 'Project', title: 'Package: preview, export, inspect, unpack as a new project', status: 'live', note: 'project pack / inspect / verify / unpack, and the same in the console. Up to 300 MiB; deterministic bytes.' },
  { id: 'PJ-05', section: 'Project', title: 'Move table data as a separate file', status: 'api', note: 'project data export / inspect / verify / import (.sbdata) are CLI-only: 16 tables, 100,000 rows, 32 MiB.' },
  { id: 'PJ-06', section: 'Project', title: 'Fork a project, and export a saved query into the folder', status: 'api', note: 'project fork and project export-query are CLI and MCP only.' },
  { id: 'PJ-07', section: 'Project', title: 'Edit the definition from the console', status: 'new', issues: [291], note: 'supabricks.toml is edited by hand. Only dataset requirements can be drafted through the platform (project dataset-draft).' },
  { id: 'PJ-08', section: 'Project', title: 'Declare sync pipelines and branches in the project', status: 'new', issues: [292], note: 'A project declares databases, migrations, fixtures, queries, notebooks, environments and dataset requirements. Sync policies and branches are runtime state and do not travel.' },
  { id: 'PJ-09', section: 'Project', title: 'Deploy to another installation by target', status: 'new', issues: [293], note: 'Targets are labels with no destination. Moving a project means exporting a package and applying it on the other machine.' },
  { id: 'PJ-10', section: 'Project', title: 'Remove retained resources', status: 'new', issues: [294], note: 'Apply is retain-only. There is no way to delete a database or installed asset whose declaration was removed.' },
  { id: 'AC-01', section: 'Access', title: 'Sign in through an identity provider (OpenID Connect)', status: 'live', note: 'The governed server signs people in with OIDC and checks tokens by introspection.' },
  { id: 'AC-02', section: 'Access', title: 'People: list, disable and enable', status: 'api', note: 'identity admin status and disable exist as request files on the server; the console has no UI.' },
  { id: 'AC-02b', section: 'Access', title: 'Email, last sign-in, and inviting someone before they sign in', status: 'new', note: 'A principal has an ID, a kind and a label. It is created at first sign-in; nothing records email or last sign-in.' },
  { id: 'AC-03', section: 'Access', title: 'Groups: create, add and remove members', status: 'api', note: 'identity admin group and membership exist on the server; the console has no UI.' },
  { id: 'AC-03b', section: 'Access', title: 'Delete or rename a group, and sync groups from the identity provider', status: 'new', note: 'Groups can only be created and have members changed. Nothing reads groups from the provider.' },
  { id: 'AC-04', section: 'Access', title: 'Service accounts: create, issue a token, revoke', status: 'api', note: 'identity admin service, issue_service and revoke exist on the server. Tokens last 1 to 3,600 seconds.' },
  { id: 'AC-04b', section: 'Access', title: 'Long-lived keys with last-used time and rotation', status: 'new', note: 'Service tokens last at most one hour and there is no key that outlives them.', issues: [249] },
  { id: 'AC-05', section: 'Access', title: 'Identity provider settings, and sign everyone out', status: 'api', note: 'identity admin configure and rotate_sessions exist on the server; the console has no UI.' },
  { id: 'AC-05b', section: 'Access', title: 'List signed-in sessions and end one', status: 'new', note: 'Sessions are stored, but can only be ended all at once or for one principal. There is no listing.' },
  { id: 'AC-06', section: 'Access', title: 'Project roles: viewer, editor, administrator for a person or group', status: 'live', note: 'set_role is available in the governed console today.' },
  { id: 'AC-06b', section: 'Access', title: 'Custom roles', status: 'new', note: 'The three roles are fixed in code.' },
  { id: 'AC-07', section: 'Access', title: 'Data permissions per branch (nine capabilities)', status: 'api', note: 'authorization admin set_data_grant exists on the server; the console has no UI.' },
  { id: 'AC-07b', section: 'Access', title: 'Direct PostgreSQL connections under a person’s own identity', status: 'new', note: 'In the governed profile PostgreSQL is private and Connect is a denied operation. No per-person credentials honour data grants.' },
  { id: 'AC-08', section: 'Access', title: 'Run permissions: run, stop anyone’s run, run as another identity', status: 'api', note: 'authorization admin set_grant exists on the server; the console has no UI.' },
  { id: 'AC-09', section: 'Access', title: 'Catalog grants per table, planned then applied', status: 'api', note: 'catalog governance plan and apply exist on the server; the console has no UI.' },
  { id: 'AC-09b', section: 'Access', title: 'Row filters and column masks', status: 'new', note: 'Catalog grants are per table only.' },
  { id: 'AC-10', section: 'Access', title: 'Audit log for the installation and for each project, with export', status: 'api', note: 'identity admin audit / audit_export and authorization admin audit exist on the server; the console has no UI.' },
  { id: 'AC-10b', section: 'Access', title: 'Audit log: time, search and filters', status: 'new', note: 'The project audit listing returns entries in order, 200 at a time, without the time of each entry and without filters.' },
  { id: 'AC-11', section: 'Access', title: 'Explain one person’s access and where it comes from', status: 'new', note: 'The policy can be read whole, but group membership is admin-only, so the console cannot resolve what one person effectively holds.' },
]

export const backing = (id: string) => BACKING.find((b) => b.id === id)

export const STATUS_LABEL: Record<BackingStatus, string> = {
  live: 'Backend ready',
  api: 'API only, no UI yet',
  new: 'Needs backend',
}
